### ISSUE TITLE
faire un chrono qui part de zéro

### ISSUE THREAD

**Issue by GuillotJessica** [valdiss/animatum#1]

**Comment by valdiss** [comment]
Pourquoi tu veux qu'il parte de 0? J'trouve ça plus clair comme ça moi, au moins là tu te doute que ça s'arrête quand t'arrive à 0 alors que si on part de 0, les joueurs savent pas quand le jeu s'arrête.

**Comment by GuillotJessica** [comment]
on pensait faire un mode chrono les enfants font le jeu sans pression et
essaie de battre leur propre record aussi pour les gamers

**Comment by valdiss** [comment]
Ah ok, le fameux mode "facile"?

**Comment by GuillotJessica** [comment]
ca peut aussi faire un mode barbu si on met les temps dans le session storage ou local storage et que le dernier reste afficher
mais ca sera dans les osef
